# Generated by Django 3.2.4 on 2021-09-23 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'M'), ('female', 'F'), ('Other', 'Other')], max_length=8, verbose_name='Gender')),
                ('plan', models.CharField(choices=[('Standard', 'Standard'), ('Basic', 'Basic'), ('Premium', 'Premium'), ('Free', 'Free')], max_length=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
            },
        ),
        migrations.CreateModel(
            name='Coachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'M'), ('female', 'F'), ('Other', 'Other')], max_length=8, verbose_name='Gender')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.coach')),
            ],
        ),
    ]
