# Generated by Django 3.2.4 on 2021-09-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='plan',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
