# Generated by Django 3.2.4 on 2021-09-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='plan',
            field=models.CharField(choices=[('Premium', 'premium'), ('Standard', 'standard'), ('Basic', 'basic'), ('Free', 'free')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
