# Generated by Django 3.2.4 on 2021-09-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_coach_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='plan',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
