# Generated by Django 3.2.4 on 2021-09-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_coach_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='plan',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Standard', 'Standard'), ('Free', 'Free')], max_length=10),
        ),
    ]
