# Generated by Django 3.2.4 on 2021-07-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210701_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coachee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coachee',
            name='list_indications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
