# Generated by Django 3.2.4 on 2021-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_coach_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='plan',
            field=models.CharField(choices=[('Free', 'free'), ('Standard', 'standard'), ('Premium', 'premium'), ('Basic', 'basic')], default='free', max_length=10),
        ),
    ]
