# Generated by Django 3.2.4 on 2021-07-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210703_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachee',
            name='list_indications',
        ),
    ]
