# Generated by Django 3.2.4 on 2021-10-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_coach_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='coach',
            name='plan',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Standard', 'Standard'), ('Free', 'Free')], max_length=10),
        ),
    ]
