# Generated by Django 3.2.4 on 2021-10-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20211004_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='plan',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Standard', 'Standard'), ('Free', 'Free'), ('Basic', 'Basic')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254, null=True),
        ),
    ]
