# Generated by Django 3.2.4 on 2021-10-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20211004_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Standard', 'Standard'), ('Basic', 'Basic'), ('Premium', 'Premium')], max_length=10),
        ),
    ]
