# Generated by Django 3.2.4 on 2021-07-05 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_coachee_list_indications'),
        ('indications', '0002_alter_indication_id'),
        ('session', '0002_auto_20210703_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.AlterField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.coach'),
        ),
        migrations.AlterField(
            model_name='session',
            name='coachee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.coachee'),
        ),
        migrations.AlterField(
            model_name='session',
            name='indications1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indication1', to='indications.indication'),
        ),
        migrations.AlterField(
            model_name='session',
            name='indications2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indication2', to='indications.indication'),
        ),
        migrations.AlterField(
            model_name='session',
            name='indications3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indication3', to='indications.indication'),
        ),
        migrations.CreateModel(
            name='AppointmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.coach')),
                ('coachee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.coachee')),
            ],
        ),
    ]
