# Generated by Django 3.2.4 on 2021-09-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indication',
            name='plan',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Standard', 'Standard'), ('Free', 'Free')], default='Free', max_length=10),
        ),
    ]
