# Generated by Django 3.2.4 on 2021-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indications', '0005_alter_indication_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='plan',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Standard', 'Standard'), ('Basic', 'Basic'), ('Free', 'Free')], default='Free', max_length=10),
        ),
    ]
