# Generated by Django 3.2.4 on 2021-10-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indications', '0011_alter_indication_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='plan',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Standard', 'Standard'), ('Free', 'Free')], default='Free', max_length=10),
        ),
    ]
